### ISSUE TITLE
String support

### ISSUE THREAD

**Issue by pedroteixeira** [madjam002/graphqlite#1]
Hi, just tried the library with the following example:

```
graphqlite.parse(`
      node(id: "123") {
        id
      }
  `)
```

throws `SyntaxError {message: "Expected ")", ",", "<", "false", "null", "true" or string but "\"" found."`

Any hints on how to use strings? thanks.

**Comment by pedroteixeira** [comment]
just noticed that strings are not supported, only a subset, correct?
will probably extend it to support some extra chars for my case for now.

**Comment by madjam002** [comment]
Yeah, strings don't require quotation marks at this point and only allow a subset of characters, but this will change in the future.

**Comment by madjam002** [comment]
@pedroteixeira Proper string support has now been added to v1.3.0, you can put strings inside quotes but there is backwards compatibility with the limited subset of characters without using quotes.

**Comment by pedroteixeira** [comment]
Nice!
