### ISSUE TITLE
isPlainObject is not defined

### ISSUE THREAD

**Issue by enriquecaballero** [madjam002/graphqlite#3]
Can't do anything with this module and would love to. I'm using webpack.

**Comment by madjam002** [comment]
Hi there,

Is there any reason specifically why you're using this repo? Now that graphql-js has been released you can just use the parser from that. This repo was for when graphql hadn't been released.

Thanks

**Comment by enriquecaballero** [comment]
Ah, thanks! Didn't inow graphql-js had a parser.
